server:
  port: 9527
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-center
  profiles:
    active: dev

encrypt:
  key-store:
    location: classpath:/my.keystore
    secret: mykeystore
    alias: mykey
    password: zhengyk
