spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100/oauth2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Yakai2020@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: zyk-microservice