spring:
  profiles:
    active: dev
  redis:
    host: 192.168.220.92
    database: 1
    password: pttlbmc
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 100
        min-idle: 0
        max-idle: 10
        max-wait: 60000

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-description: 生产者
  application-version: 0.0.1
  try-host: http://localhost:${server.port}
history-log:
  enabled: true