spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: requestratelimiter_route
          uri: https://www.baidu.com
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@ipKeyResolver}"
          predicates:
            - Method=GET

  redis:
    host: 192.168.220.92
    database: 1
    password: pttlbmc
    port: 6379
    timeout: 20000
