#spring:
#  mail:
#    #smtp服务主机  qq邮箱则为smtp.qq.com
#    host: smtp.163.com
#    #服务协议
#    protocol: smtp
#    # 编码集
#    default-encoding: UTF-8
#    #发送邮件的账户
#    username: yakai512@163.com
#    #授权码
#    password: kai8611016
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#async:
#  thread-name-prefix: exception-email-
